### ISSUE TITLE
Invalid client signature

### ISSUE THREAD

**Issue by apps4u** [MobileFirst-Platform-Developer-Center/EnrollmentAndroid#1]
Hi Ive been using MobileFirst 8 on a windows server Ive got it on my Mac as well and Ive tried on Bluemix.

Ive been able to get App's running but not if I had security , So Today I download each of the samples on in the Git Org for Android and I can register and push and pull the config , Ive built in deploy the Security Adapters but when ever I run any of the samples I get a error . "Invalid client signature" . Now Ive been getting this error on my mac and on the Windows server.  I created my own key store thinking that would help but it did not. I can get tokens via Postman but I can not run any of your sample that require Auth . I used to think it was the Widnows server as it was on AWS VM so the simulator was real slow, But Im on a brand new Mac core i7 16GB , 1TB Flash 5K monitor so this is real quick and has no issues running the simulator. I really want to start moving my clients mobiles to MobileFirst so I can get rid of heap of micro services that are just running so I can proxy data for other servers . But I'm sure Im not doing any thing Wrong as Ive did a fresh install of version 8 server I installed the Security Adapters and The Adapters repo so I have all the adapters install and I'm running your sample code without any changes. The Application are all registered and I have pushed all of them so there scopes are setup correctly , I can also get a token via Postman and Idea IntelJ REST Client. 

Please help I created a few Adapters over the last few months to show clients the benefits of MobileFirst and I came back to the issue of Security today as I though it was the AWS server with the issue but It the same on my mac , I need to be able to show them a working example with security in place Ive created a package to add security to there resource server. So Please help this is all that stopping me from getting my clients to agree to move.

**Comment by NathanHazout** [comment]
That's a lot of text, it's a bit confusing...

Can we try to summarize? Let's remove unknowns such as AWS in the story.
- Where is the "client" running (android emulator? On the mac?)
- Where is the MFP server running? (on that same machine? a different one?)
- Are you always getting that error? Even with the simplest samples such as ResourceRequest?

The error  "Invalid client signature" means that something went wrong during the registration of the device against the server.

**Comment by apps4u** [comment]
Sorry 
Ok Ive not been able to get any of your sample application or mine to working if they use Security,
 Ive tried the PinCode , Login etc.

Now as I said at first I thought it was the server I was on but thats not the case , So Ive created some of my own Adapters and I could not get login working. So today I did a fresh install Mobilefirst 8, I installed all the Sample Adapter in this Org , and I downloaded all the sample apps or 4 of them , for Android and IOS all keep giving me the same error.

All apps are registered I can connect to any Adapter that dose not use Security, As soon as I add a scope to the Adapter resource It fails with the same error.

**Comment by apps4u** [comment]
[{"threadID":1011,"sourceMethodName":"","stacktrace":["com.ibm.mfp.server.security.shared.webtoken.JWS.fromHeaderPayloadSignature(JWS.java:116)","com.ibm.mfp.server.registration.internal.RegistrationServiceImpl.verifySignedData(RegistrationServiceImpl.java:80)","sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)","sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","java.lang.reflect.Method.invoke(Method.java:498)","org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)","org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)","org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)","org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)","org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)","org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)","org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)","com.sun.proxy.$Proxy206.verifySignedData(Unknown Source)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl.doSelfRegistration(RegistrationEndpointImpl.java:107)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl.access$000(RegistrationEndpointImpl.java:58)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl$1.call(RegistrationEndpointImpl.java:92)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl$1.call(RegistrationEndpointImpl.java:89)","com.ibm.mfp.server.persistency.internal.transaction.StorageManagerImpl.doWithStorage(StorageManagerImpl.java:48)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl.selfRegistration(RegistrationEndpointImpl.java:89)","sun.reflect.GeneratedMethodAccessor144.invoke(Unknown Source)","sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","java.lang.reflect.Method.invoke(Method.java:498)","org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)","org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)","org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)","org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)","org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)","org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)","org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)","org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)","org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)","org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)","javax.servlet.http.HttpServlet.service(HttpServlet.java:707)","org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)","javax.servlet.http.HttpServlet.service(HttpServlet.java:790)","com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1287)","com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:778)","com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:475)","com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:150)","com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)","com.ibm.mfp.server.core.internal.analytics.AnalyticsTrackingFilter.doFilter(AnalyticsTrackingFilter.java:49)","org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)","org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)","com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207)","com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)","com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1020)","com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1142)","com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:81)","com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:928)","com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:262)","com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:955)","com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:341)","com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:470)","com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:404)","com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:284)","com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:255)","com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:174)","com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:83)","com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)","com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)","com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:929)","com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1018)","java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)","java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)","java.lang.Thread.run(Thread.java:745)"],"level":"ERROR","timezone":0,"sourceClass":"com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl","loggerName":"com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl","message":"Client registration failed - invalid signature.","timestamp":"24-07-16 07:47:59:769","trackingID":"cd9e967f-2f26-4982-9d02-36833ab115d9"},{"threadID":738,"sourceMethodName":"","stacktrace":["com.ibm.mfp.server.security.shared.webtoken.JWS.fromHeaderPayloadSignature(JWS.java:116)","com.ibm.mfp.server.registration.internal.RegistrationServiceImpl.verifySignedData(RegistrationServiceImpl.java:80)","sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)","sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","java.lang.reflect.Method.invoke(Method.java:498)","org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)","org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)","org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)","org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)","org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)","org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)","org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)","com.sun.proxy.$Proxy206.verifySignedData(Unknown Source)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl.doSelfRegistration(RegistrationEndpointImpl.java:107)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl.access$000(RegistrationEndpointImpl.java:58)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl$1.call(RegistrationEndpointImpl.java:92)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl$1.call(RegistrationEndpointImpl.java:89)","com.ibm.mfp.server.persistency.internal.transaction.StorageManagerImpl.doWithStorage(StorageManagerImpl.java:48)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl.selfRegistration(RegistrationEndpointImpl.java:89)","sun.reflect.GeneratedMethodAccessor144.invoke(Unknown Source)","sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","java.lang.reflect.Method.invoke(Method.java:498)","org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)","org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)","org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)","org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)","org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)","org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)","org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)","org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)","org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)","org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)","javax.servlet.http.HttpServlet.service(HttpServlet.java:707)","org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)","javax.servlet.http.HttpServlet.service(HttpServlet.java:790)","com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1287)","com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:778)","com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:475)","com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:150)","com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)","com.ibm.mfp.server.core.internal.analytics.AnalyticsTrackingFilter.doFilter(AnalyticsTrackingFilter.java:49)","org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)","org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)","com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207)","com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)","com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1020)","com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1142)","com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:81)","com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:928)","com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:262)","com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:955)","com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:341)","com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:470)","com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:404)","com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:284)","com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:255)","com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:174)","com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:83)","com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)","com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)","com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:929)","com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1018)","java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)","java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)","java.lang.Thread.run(Thread.java:745)"],"level":"ERROR","timezone":0,"sourceClass":"com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl","loggerName":"com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl","message":"Client registration failed - invalid signature.","timestamp":"24-07-16 07:47:58:140","trackingID":"13196ab6-e65b-44cf-a7fb-5e4b03110500"},{"threadID":861,"sourceMethodName":"","stacktrace":["com.ibm.mfp.server.security.shared.webtoken.JWS.fromHeaderPayloadSignature(JWS.java:116)","com.ibm.mfp.server.registration.internal.RegistrationServiceImpl.verifySignedData(RegistrationServiceImpl.java:80)","sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)","sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","java.lang.reflect.Method.invoke(Method.java:498)","org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)","org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)","org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)","org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)","org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)","org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)","org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)","com.sun.proxy.$Proxy206.verifySignedData(Unknown Source)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl.doSelfRegistration(RegistrationEndpointImpl.java:107)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl.access$000(RegistrationEndpointImpl.java:58)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl$1.call(RegistrationEndpointImpl.java:92)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl$1.call(RegistrationEndpointImpl.java:89)","com.ibm.mfp.server.persistency.internal.transaction.StorageManagerImpl.doWithStorage(StorageManagerImpl.java:48)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl.selfRegistration(RegistrationEndpointImpl.java:89)","sun.reflect.GeneratedMethodAccessor144.invoke(Unknown Source)","sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","java.lang.reflect.Method.invoke(Method.java:498)","org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)","org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)","org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)","org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)","org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)","org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)","org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)","org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)","org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)","org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)","javax.servlet.http.HttpServlet.service(HttpServlet.java:707)","org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)","javax.servlet.http.HttpServlet.service(HttpServlet.java:790)","com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1287)","com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:778)","com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:475)","com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:150)","com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)","com.ibm.mfp.server.core.internal.analytics.AnalyticsTrackingFilter.doFilter(AnalyticsTrackingFilter.java:49)","org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)","org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)","com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207)","com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)","com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1020)","com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1142)","com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:81)","com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:928)","com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:262)","com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:955)","com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:341)","com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:470)","com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:404)","com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:284)","com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:255)","com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:174)","com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:83)","com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)","com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)","com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:929)","com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1018)","java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)","java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)","java.lang.Thread.run(Thread.java:745)"],"level":"ERROR","timezone":0,"sourceClass":"com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl","loggerName":"com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl","message":"Client registration failed - invalid signature.","timestamp":"24-07-16 07:47:16:960","trackingID":"86177a7a-dfdc-4634-bcf2-3c89ee61d8e3"},{"threadID":953,"sourceMethodName":"","stacktrace":["com.ibm.mfp.server.security.shared.webtoken.JWS.fromHeaderPayloadSignature(JWS.java:116)","com.ibm.mfp.server.registration.internal.RegistrationServiceImpl.verifySignedData(RegistrationServiceImpl.java:80)","sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)","sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","java.lang.reflect.Method.invoke(Method.java:498)","org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)","org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)","org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)","org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)","org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)","org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)","org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)","com.sun.proxy.$Proxy206.verifySignedData(Unknown Source)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl.doSelfRegistration(RegistrationEndpointImpl.java:107)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl.access$000(RegistrationEndpointImpl.java:58)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl$1.call(RegistrationEndpointImpl.java:92)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl$1.call(RegistrationEndpointImpl.java:89)","com.ibm.mfp.server.persistency.internal.transaction.StorageManagerImpl.doWithStorage(StorageManagerImpl.java:48)","com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl.selfRegistration(RegistrationEndpointImpl.java:89)","sun.reflect.GeneratedMethodAccessor144.invoke(Unknown Source)","sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","java.lang.reflect.Method.invoke(Method.java:498)","org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)","org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)","org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)","org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)","org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)","org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)","org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)","org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)","org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)","org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:868)","javax.servlet.http.HttpServlet.service(HttpServlet.java:707)","org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)","javax.servlet.http.HttpServlet.service(HttpServlet.java:790)","com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1287)","com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:778)","com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:475)","com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:150)","com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:93)","com.ibm.mfp.server.core.internal.analytics.AnalyticsTrackingFilter.doFilter(AnalyticsTrackingFilter.java:49)","org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)","org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)","com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:207)","com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90)","com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:1020)","com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1142)","com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:81)","com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:928)","com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:262)","com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:955)","com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:341)","com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:470)","com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:404)","com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:284)","com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:255)","com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:174)","com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:83)","com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)","com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)","com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:929)","com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1018)","java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)","java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)","java.lang.Thread.run(Thread.java:745)"],"level":"ERROR","timezone":0,"sourceClass":"com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl","loggerName":"com.ibm.mfp.server.registration.internal.rest.RegistrationEndpointImpl","message":"Client registration failed - invalid signature.","timestamp":"24-07-16 07:47:12:477","trackingID":"2810cd2f-f6e4-4b4f-8fc0-51e723aad832"}]

**Comment by apps4u** [comment]
To replete my steps
1 install mobile first..
2 install all adapter in the SecurityAdapters repo.
3 install and setup all the Adnpters repo.
4 download and run sample Android Application.

I use MFPDEV to register and push the mobile application's (PinCode, Login Remember Me, PreemptiveLogin, Enrollment) non of these sample work.

I i access a unprotected resource it works. but none of the above sample working on Android or IOS. The error in the Analytic dash board said  "Invalid client signature"

**Comment by apps4u** [comment]
All running on my mac , server, and android emulator is running on mac, I run the IOS apps in the simulator and on iPad. All every thing on the mac. I can try the server in a docker container if you think that would help

**Comment by apps4u** [comment]
Just a quick update , This may be the issue, Ive just created new space on Bluemix and install MobileFirst , this time it worked as last week each time I created the service it would error out saying route could not be created any way it install and I tried to run all the sample and my Adaapters and they all worked.
So it seems to be the local development server that is not able to run so It could be that the client SDK are newer then the dev server I have. The local dev server I'm running is version  8 But it only has options for Android , IOS, Windows Mobile apps the version on bluemix also has web application's so I't newer then the server I have.

**Comment by IdanAdar** [comment]
If you run a local installation of MobileFirst Server by using the devkit installer - note that it is incompatible with the current Client SDKs that are available online. For now you must use the Mobile Foundation Bluemix service until updated devkit installers are released. Please re-open the issue if you continue to experience issues also with the Bluemix service. When the updated installers are available, a blog post will be published in the MobileFirst Foundation developer center.

**Comment by apps4u** [comment]
Thanks I just going to dig up older version of the sdk's if not I'll use Bluemix . I want to get my clients to move so I just needed a running version I could show them thanks for help on a Sunday.
